# Clock bridge: Gz -> ROS2
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  lazy: "False"
  direction: "GZ_TO_ROS"
  qos_profile: "CLOCK"

# LiDAR bridge: Gz -> ROS2
- ros_topic_name: "/lidar_front/points_raw"
  gz_topic_name: "/lidar_front/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

# Camera bridge: Gz -> ROS2
# Stereo bridge: Gz -> ROS2
